filters:
  global:
    ignore_ports: []  # конкретные порты, которые игнорируем на всех устройствах (например g0/10)
    ignore_patterns:   # паттерны для 10Gb портов
      - "tg"
      - "te"
      - "xe"
      - "TenGigabitEthernet"
      - "TwentyGigabitEthernet"
      - "FortyGigabitEthernet"
      - "HundredGigabitEthernet"
      - "po"

  devices:  # конкретные устройства (по IP)
    10.60.10.1:   # core
      ignore_ports:
        - "g1/0/6"
        - "g1/0/8"
        - "g1/0/11"
        - "g1/0/12"
        - "g1/0/13"
        - "g1/0/14"
        - "g1/0/17"
        - "g1/0/18"
        - "g1/0/20"
        - "g1/0/37"
        - "g1/0/38"
        - "g1/0/40"
        - "g2/0/38"
        - "g2/0/39"
        - "g2/0/40"
        - "g2/0/41"
        - "g2/0/42"
        - "g2/0/43"
        - "g2/0/44"
        - "g2/0/45"
        - "g2/0/46"
        - "g2/0/47"
        - "g2/0/48"
        - "g3/0/48"
        - "tg1/1/8"
        - "tg1/1/1"
        - "tg1/1/2"
        - "tg1/1/3"
        - "tg1/1/4"
        - "tg1/1/5"
        - "tg1/1/6"
        - "tg1/1/7"
        - "tg1/1/8"
        - "tg2/1/8"
        - "tg2/1/1"
        - "tg2/1/2"
        - "tg2/1/3"
        - "tg2/1/4"
        - "tg2/1/5"
        - "tg2/1/6"
        - "tg2/1/7"
        - "tg2/1/8"
        - "tg3/1/8"
        - "tg3/1/1"
        - "tg3/1/2"
        - "tg3/1/3"
        - "tg3/1/4"
        - "tg3/1/5"
        - "tg3/1/6"
        - "tg3/1/7"
        - "tg3/1/8"

    10.65.10.1:
      ignore_ports:
        - "po1"
        - "po2"
        - "po3"
        - "po4"
        - "g1/0/4"
        - "g1/0/10"
        - "g1/0/12"
        - "g1/0/14"
        - "g1/0/16"
        - "g1/0/18"
        - "g2/0/10"
        - "g2/0/12"
        - "g2/0/14"
        - "g2/0/16"
        - "tg1/0/3"
        - "tg2/0/6"

    10.65.10.51:
      ignore_ports:
        - "tg2/0/1"

        
    10.66.10.1:   # core
      ignore_ports:
        - "g0/10"
        - "g0/11"
        - "g0/12"
        - "g0/29"
        - "g0/30"

    10.68.10.1:
      ignore_ports:
        - "g0/9"

    "*":  # fallback для всех остальных устройств
      ignore_ports: []